### PR TITLE
Fix RPL_WHOREPLY response

### LINKED ISSUE #53: Invalid RPL_WHOREPLY for Gitter Bot
Here's a quick example.

Let's say we run `/who #GlowstonePlusPlus/GlowstonePlusPlus`, We'll get our stack of `RPL_WHOREPLY` messages, as expected.

`:irc.gitter.im 352 <my username> #GlowstonePlusPlus/GlowstonePlusPlus <their username> irc.gitter.im irc.gitter.im Egoscio H :0 <their realname>`

However, when we get to `gitter`, we get the following response:

`:irc.gitter.im 352 gdude2002 #GlowstonePlusPlus/GlowstonePlusPlus gitter :irc.gitter.im irc.gitter.im gitter H :0 Gitter Bot`

Note the extra `:` after `gitter ` and before `irc.gitter.im`.

Is there a reason for this? It seems to be breaking the parsing for various IRC bot frameworks.

### PR DESCRIPTION
**Pull request by gdude2002**
Fix RPL_WHOREPLY response

Fixes #53

### CODE REVIEW

**Comment by MadLittleMods** [comment]
Update your commit message to be more descriptive. Something like `Fix RPL_WHOREPLY response`

**Comment by gdude2002** [comment]
Here you go

**Comment by gdude2002** [comment]
@MadLittleMods @mydigitalself Is this PR destined to just die in a black hole? It's a one-word change :P

By the way, that `gitter-irc` chek has been sitting at `Waiting for status to be reported` since the PR was opened. It's marked as `Required`, so what gives?

**Comment by MadLittleMods** [comment]
@gdude2002 We just haven't had a chance to test it out. What is a good way to confirm the fix?

**Comment by gdude2002** [comment]
@MadLittleMods I'm not sure about how you might unit-test it, but if you want to verify it yourself, grab an IRC bot or client that outputs raw lines, and send a `WHO #Org/repo` for any channel you're on. The `RPL_WHOREPLY` that the server sends you for `gitter` should only contain one `:` right at the start of the message, and nowhere else.

You could also just use `telnet`.

**Comment by Fryguy** [comment]
FWIW I made this change locally, ran the irc-bridge, and successfully connected my client (i.e. I don't see my error from https://github.com/gitterHQ/gitter/issues/1260 anymore)

**Comment by MadLittleMods** [comment]
@Fryguy Really appreciate the reply, gives us more confidence!

**Comment by Fryguy** [comment]
I tried to write test but testing this requires stubbing the gitterClient (or truly talking to gitter), and I just couldn't figure out how to that properly.  None of the other tests really do client-adapter-gitter integration tests.

**Comment by Gargaj** [comment]
This is a pretty obvious merge; RFC (https://tools.ietf.org/html/rfc2812#page-47) says the only the hop-reply must be prefixed with colon; ```c.host``` is the prefixed version of ```c.hostname```.

**Comment by Gargaj** [comment]
You can also test it fairly easily: connect to the current active IRC bridge and do a ```/who #gitterHQ/irc-bridge```:
```
[...]
<- :irc.gitter.im 352 Gargaj #gitterHQ/irc-bridge memopower irc.gitter.im irc.gitter.im memopower H :0 memopower
<- :irc.gitter.im 352 Gargaj #gitterHQ/irc-bridge Jacob843 irc.gitter.im irc.gitter.im Jacob843 H :0 Jacob
<- :irc.gitter.im 352 Gargaj #gitterHQ/irc-bridge gitter :irc.gitter.im irc.gitter.im gitter H :0 Gitter Bot
<- :irc.gitter.im 315 Gargaj #gitterHQ/irc-bridge :End of /WHO list.
```
You can see the last line for the gitter-bot has an extra colon in it.

**Comment by gdude2002** [comment]
I'm still wondering about that `gitter-irc` hanging check there. I'm hoping that isn't what's stopping this from being merged - it's one of the most trivial changes I can think of.

**Comment by MadLittleMods** [comment]
:+1: Got this tested now. Using Hexchat I see an extra colon but curiously only on the last result intstead of all of them as I would expect ([just as @Gargaj saw](https://github.com/gitterHQ/irc-bridge/pull/54#issuecomment-224080660))

Current (notice extra colon):

```
#gitterHQ/irc-bridge suprememoocow irc.gitter.im irc.gitter.im suprememoocow H :0 Andrew Newdigate
#gitterHQ/irc-bridge MadLittleMods irc.gitter.im irc.gitter.im MadLittleMods H :0 Eric Eastwood
#gitterHQ/irc-bridge gitter :irc.gitter.im irc.gitter.im gitter H :0 Gitter Bot
```

With this PR:

```
#gitterHQ/irc-bridge suprememoocow irc.gitter.im irc.gitter.im suprememoocow H :0 Andrew Newdigate
#gitterHQ/irc-bridge MadLittleMods irc.gitter.im irc.gitter.im MadLittleMods H :0 Eric Eastwood
#gitterHQ/irc-bridge gitter irc.gitter.im irc.gitter.im gitter H :0 Gitter Bot
```

**Comment by MadLittleMods** [comment]
Thanks for the issue and PR @gdude2002, sorry about the long wait :sweat_smile:

**Comment by Fryguy** [comment]
\o/ Thanks @MadLittleMods !

**Pull request merged**
