### PR TITLE
Use skip API to get all users in channel (room).

### PR DESCRIPTION
**Pull request by choppsv1**
Fixes issue #52

### CODE REVIEW

**Comment by The-Compiler** [comment]
Any update on this? It's quite annoying that everyone talking is offline in bigger channels - I don't see nick colors, and I can't tab-complete nicks.

**Comment by MadLittleMods** [comment]
Fix up the conflicts. Is the best way to test this to just run your own instance and connect via a IRC client?

**Comment by choppsv1** [comment]
I updated this branch and got no conflicts.. I'm not using this sw anymore though.

**Comment by MadLittleMods** [comment]
Unfortunately, we can't move forward with this one because there would be too many requests going out for some rooms.

We limited the room members endpoint to a default of 30 for performance in the first place and trying to paginate through the API with a 60k member room like FreeCodeCamp is just not viable. To note, the max `limit` is 100 so that puts less strain and is less blocking.

---

We could slowly add members over time for the people who chatted in the room. So every time a message is sent, we add the author/sender to the member list.

Also just throwing it out there about using `/NAMES` might be a decent indicator to fill in some members. Calling `/NAMES #gitterHQ/irc-bridge` for example could populate the members for `gitterHQ/irc-bridge` but this still has issues for very large rooms.

**Comment by choppsv1** [comment]
What if we add a upper limit of 5k or so? The first 30 or even 100 in larger rooms basically covers somewhere between none and 1 or 2 active folks in the room. The largest impact I think is on nick recognition (e.g., completion of nicks when hitting tab). For a while I'd also hacked my client to just add users as it saw them, then I decided to just give up on the bridge and use the standalone gitter app.

**Comment by MadLittleMods** [comment]
I think that adding members over time is the way to go especially for now. This captures a nice portion of people you would be interacting with.

I'd be open to merging that PR if you want to create a new one.

**Comment by The-Compiler** [comment]
> We could slowly add members over time for the people who chatted in the room. So every time a message is sent, we add the author/sender to the member list.

That sounds like a great proposal. My main gripe is that I don't have nick colors (as offline people are all red in my client) and can't tab-complete people who are talking.

**Pull request closed without merging**
