### PR TITLE
Misc IRC standards compliance fixes

### PR DESCRIPTION
**Pull request by dequis**
Or, rather, just a few odd things I spotted. But "standards compliance" sounds better.

I think the lack of 005 RPL_ISUPPORT was causing issues in some clients, but I don't remember which or what issues.

### CODE REVIEW

**Comment by MadLittleMods** [comment]
@dequis Can you link to the RFC spec where you are fixing things?

Also would appreciate if you can recall which client had issues, so I can test.

**Comment by dequis** [comment]
Not everything is in a proper RFC, because irc is like that. In particular RFC2812 (which seems to be what this implementation follows, given the 001-004 numerics but no 005) has a lot of parts that are specific to ircnet's implementation that no one else picked up. The 005 numeric of RFC2812 isn't even followed by ircnet themselves - they use RPL_ISUPPORT.

That being said, the latest RPL_ISUPPORT draft is https://tools.ietf.org/html/draft-hardy-irc-isupport-00 (it never became a RFC, but it's probably one of the most faithfully implemented irc specs, probably more than rfc1459 and rfc2812)

The 403 numeric parameters are in https://tools.ietf.org/html/rfc2812#section-5.2

The ERROR verb is in https://tools.ietf.org/html/rfc2812#section-3.7.4

The `*` target thing, well, i owe you that one. But you easily see that one in any other server:

```
$ nc -v irc.freenode.net 6667
Connection to irc.freenode.net 6667 port [tcp/*] succeeded!
:asimov.freenode.net NOTICE * :*** Looking up your hostname...
:asimov.freenode.net NOTICE * :*** Checking Ident
:asimov.freenode.net NOTICE * :*** Found your hostname
```

The third parameter is `*`.

Here's a nice site describing the general situation of the IRC specs: http://ircdocs.horse/specs/

Here's a full list of numerics: http://defs.ircdocs.horse/defs/numerics.html

And a full list of RPL_ISUPPORT tokens that aren't mentioned in the original draft: http://defs.ircdocs.horse/defs/isupport.html

**Comment by MadLittleMods** [comment]
@dequis Can you fix up the conflicts?

Also moving some of that info in a comment under each change in the diff will help understanding the spec compliance benefit.

**Comment by dequis** [comment]
Rebased and edited commit messages to add relevant links.

**Comment by dequis** [comment]
This thing said it was outdated so i rebased again, no changes. Also hi.

**Comment by mydigitalself** [comment]
@dequis hi. sorry, we lost the maintainer of this project and are picking it up again. would you mind updating and i'll take a look.

**Comment by dequis** [comment]
>we lost the maintainer of this project

RIP.

I thought there were merge conflicts (gray merge icon mislead me) but it was just a clean rebase.

**Pull request merged**
